### ISSUE TITLE
Mouse cursor visibility

### ISSUE THREAD

**Issue by AneMou** [DeveloppeurPascal/Sporgloo#69]
### I miss the mouse's cursor T -T)

**Encountered issue:**
I'd like to see the mouse cursor in order to see when exactly I'm leaving or entering a cell.
It reduces the player's precision, and there are times when I click the wrong cell when I'm trying to anticipate.

**Prefered solution:**
Simply enabling mouse cursor visibility

![mouse_cursor_visibility](https://github.com/DeveloppeurPascal/Sporgloo/assets/140966836/6ea5944f-1409-47d3-b302-234f61897960)

**Comment by DeveloppeurPascal** [comment]
ajouter le choix d'afficher ou pas le curseur de la souris en phase de jeu (dans les options du jeu)
